services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./audio_files:/app/audio_files
      - ./processed_data:/app/processed_data
      - ./data:/app/data
    environment:
      - DATABASE_URL=duckdb:///app/data/audio_data.duckdb
      - WHISPER_MODEL_SIZE=base
      - ENVIRONMENT=development
    depends_on:
      - redis
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: 